# action.yml
name: 'Terraform Crawler'
description: 'Find usage of a module'
inputs:
  changedFilesList:
    description: 'A json encoded list of modified files'
    required: true
    default: '[]'
outputs:
  target_folders:
    description: 'The folders where we a going to run terraform'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filepath }}
