# action.yml
name: 'Terraform Crawler'
description: 'Find usage of a module'
inputs:
  filepath:
    description: 'the path to the json file that contains the list of modified files'
    required: true
    default: 'dummy.json'
outputs:
  target_folders:
    description: 'The folders where we a going to run terraform'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filepath }}
